### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-semantic-html#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://aware-queen.surge.sh/).
I'm not sure if I did articles and sections in the best way. I'm not getting errors, but I am getting warnings.

**Comment by chrisvfritz** [comment]
Yeah, I would leave out the `section`s in your `article`s in this case, because the `section` here really just means the main body of your content. More typically, a `section` element would be used to define multiple sections within your content. Does that make sense?

Also, in order to play your video, I had to right click on it and then click "Play" - which isn't a great user experience. Most users probably wouldn't even notice that it was a video. There's a simple way to fix this though and make it behave like a more typical video on the Internet: [the `controls` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-controls). That link is to the Mozilla Developers Network's page on the `video` element. This is probably my favorite resource for learning more about specific HTML elements! :smiley:

Make those two fixes and I'll approve this pronto.

**Comment by KatieMFritz** [comment]
[New url](http://hideous-quilt.surge.sh/)

Added controls to the video and got rid of sections within articles. I kept the header and footer elements within articles; is that cool?

**Comment by chrisvfritz** [comment]
Love it! :shipit: The `header` and `footer` elements within articles are within the spec, so they can stay. Great work. :tada: :balloon: :smile_cat:
